#!/bin/bash
PRIMARY_IP=$(hostname -I | awk '{print $1}')

# Primary IP for Nginx configuration
sed -i "s/PRIMARY_IP/$PRIMARY_IP/" ./nginx/nginx.conf

# Substitute primary IP for IRIS server communication
sed -i "s/PRIMARY_IP/$PRIMARY_IP/" ./velociraptor/add_iris_velo_module

# Build images
docker compose --profile "elastic" --profile "intelowl" --profile "iris" build

# Start everything up
docker compose --profile "elastic" --profile "intelowl" --profile "iris" up -d

# Sleep for a minute
echo "Sleeping for 60s to ensure services are online before proceeding..."
sleep 60s

# Add IRIS Velociraptor module
./velociraptor/add_iris_velo_module

