apiVersion: v1
kind: Service
metadata:
  namespace: iris-web
  name: iris-psql-service
  labels:
    site: iris
spec:
  selector:
    app: iris-psql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
