apiVersion: v1
kind: Service
metadata:
  namespace: iris-web
  name: iris-worker-service
  labels:
    site: iris
spec:
  selector:
    app: iris-worker
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP
