# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iris-web
  name: iris-app-deployment
  labels:
    site: iris
    app: iris-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-app
  template:
    metadata:
      labels:
        app: iris-app
    spec:
      containers:
      - name: iris-app
        image: iriswebapp_app:v2.2.2
        ports:
        - containerPort: 8000
        command: ['nohup', './iris-entrypoint.sh', 'iriswebapp'] 
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: POSTGRES_PASSWORD
          - name: POSTGRES_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: POSTGRES_ADMIN_USER
          - name: POSTGRES_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: POSTGRES_ADMIN_PASSWORD
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: POSTGRES_PORT
          - name: DOCKERIZED
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: DOCKERIZED
          - name: IRIS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: IRIS_SECRET_KEY
          - name: IRIS_SECURITY_PASSWORD_SALT
            valueFrom:
              secretKeyRef:
                name: iris-app-secrets
                key: IRIS_SECURITY_PASSWORD_SALT

          - name: POSTGRES_SERVER
            valueFrom:
              configMapKeyRef:
                name: app-data
                key: POSTGRES_SERVER
        volumeMounts:
        - name: iris-pcv
          mountPath: /home/iris/downloads
          subPath: downloads
        - name: iris-pcv
          mountPath: /home/iris/user_templates
          subPath: user_templates
        - name: iris-pcv
          mountPath: /home/iris/server_data
          subPath: server_data
      volumes:
      - name: iris-pcv
        persistentVolumeClaim:
          claimName: iris-psql-claim